### PR TITLE
Fields that have their default values are missing from Protobuf messages in 22.6.0. Assign default values if missing. (Hack!)

### PR DESCRIPTION
**Pull request by FeepingCreature**
Due to [1], fields that have their default values are now missing from Protobuf messages. Fill those fields in with proto3 default values instead of erroring.

[1] https://github.com/EventStore/EventStore/issues/3625

### CODE REVIEW

**Comment by nicdex** [comment]
has this been tested for backward compatibility?

**Comment by FeepingCreature** [comment]
No, but it's hard to see how it could fail: it only changes the error case.

**Comment by nicdex** [comment]
Sorry about the delay, but I had to prioritise fixing compatibility with 21.10 which is the latest LTS. I will try to get to this later this week.

**Comment by FeepingCreature** [comment]
That's fine, thank you!

**Comment by nicdex** [comment]
Closing this. I just finished deploying all versions compatible with EventStore LTS verions.
If you are using 22.10.x then use `npm install --save node-eventstore-client@^22.10`

**Pull request closed without merging**
